{
 "title": "TP-Truck | Platform Overview",
 "tags": [
  "tp-truck",
  "logistics"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "env", "query": "dev,uat,prod" }
  ]
 },
 "panels": [
  {
   "title": "API Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(up{job=\"truck-fleet-app\"})"
    }
   ]
  },
  {
   "title": "Request Rate (req/s) by URI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"truck-fleet-app\"}[1m])) by (uri)"
    }
   ]
  },
  {
   "title": "p95 Latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{job=\"truck-fleet-app\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "5xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"truck-fleet-app\",status=~\"5..\"}[5m]))"
    }
   ]
  },
  {
   "title": "JVM Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"truck-fleet-app\",area=\"heap\"})"
    }
   ]
  },
  {
   "title": "HikariCP Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "hikaricp_connections_active{job=\"truck-fleet-app\"}"
    }
   ]
  }
 ]
}