apiVersion: apps/v1
kind: Deployment
metadata:
  name: truck-fleet
  labels:
    app: truck-fleet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: truck-fleet
  template:
    metadata:
      labels:
        app: truck-fleet
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: truck-fleet
          image: ghcr.io/truck-manager-tp/truck-fleet:1.0.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: truck-fleet-config
            - secretRef:
                name: truck-fleet-db
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 15
